### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by kadel** [redhat-developer/henge#25]
Right now Hange has only commandline interface.

But it would be nice to have API for this.

My inital proposal is to create daemon mode for Henge.
In this mode henge would expose json rest api on given port.

In code we need to define abstractions so we have consistency between cmdline and rest api.

**Subtasks:**
 - [ ] design rest api interface
 - [ ] code refactoring to keep rest api and cmdline consistent 
 - [ ] create henge deamon mode

**Comment by rtnpro** [comment]
:+1:

**Comment by surajssd** [comment]
This can be hosted and people can use from a web front end or command line curl, so helps us getting more users.

**Comment by kadel** [comment]
> This can be hosted and people can use from a web front end or command line curl, so helps us getting more users.

Yes this could be done in the future, but people still need to be able to run api server on their own.
